# Author's infomation
title: Chuan's personal website
description: My personal stack problems and solutions
github: https://github.com/cqin-zz
baseurl: "" # the subpath of your site, e.g. /blog
url: "cqin-zz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
locale: "en-US"

author:
  name: Chuan Qin
  about: Planning Engineer & PSRT Lead at NYISO
  email: cqin@nyiso.com
  location: Rensselaer, NY
  portfolio_image: "portfolio.png"
  googlescholar: https://scholar.google.com/citations?user=A4QD9RgAAAAJ&hl=en

enableTags: true
tagarray: []

collections:
  publication:
    output: true
    permalink: /publication/:path/
  project:
    output: true
    permalink: /project/:path/
  notes:
    output: true
    permalink: /notes/:path/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/chuan.qin.7545"
    - icon: fa-instagram
      link: "https://www.instagram.com/sxxnqc/"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/chuan-qin-18b086158/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/cqin-zz"
    - icon: fa-google-scholar
      link: "https://scholar.google.com/citations?user=A4QD9RgAAAAJ&hl=en"
    - icon: fa-email
      link: "mailto:chuan.qin@ieee.org"
     
share:
  twitter_username: github.io
  fb_appid: 1749788565247320
  
urls:
    - text: My Publications
      url: /publications/
    - text: My Projects
      url: /projects/
    - text: My Notes
      url: /notes/
    
#Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist

paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']